name: Deploy Laravel to Railway

on:
  push:
    branches:
      - main   # jalankan setiap kali push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate --force

      - name: Run migrations
        env:
          DB_CONNECTION=mysql
          DB_HOST=mysql.railway.internal
          DB_PORT=3306
          DB_DATABASE=railway 
          DB_USERNAME=root
          DB_PASSWORD=uzVmjvdUDosJUiIaSqEzDUeaYsgNYUkD
        run: php artisan migrate --force
